# Generated by Django 3.2.6 on 2021-08-12 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 36, 24, 68487)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 36, 24, 67085)),
        ),
    ]
