# Generated by Django 3.2.6 on 2021-08-12 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210812_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 39, 45, 661731)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 17, 39, 45, 660389)),
        ),
    ]
