# Generated by Django 3.2.6 on 2021-08-13 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210813_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='flActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 8, 46, 51, 307610)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 8, 46, 51, 306064)),
        ),
    ]
